    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Copy index.html to Apache web root
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Apache is running and enabled on boot
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
